#!/bin/sh
#/**
#  * <div class="p">
#  * 'Controller' script for the <a
#  *   href="http://dogfoodsoftware.com/documentation/conveyor/ref/Branching-Strategy">Conveyor
#  *   branch strategy</a> extensions. Please refer to the branch strategy
#  *   documentation for details on usage.
#  * </div>
#  * <div id="Implementation" data-perspective="implementation" class="grid_12 blurbSummary">
#  *   <div class="blurbTitle">Implementation</div>
#  *   <div class="p">
#  *     This script essentially reads the first argument&mdash;which is
#  *     understood as the resource name&mdash;and then looks for the matching
#  *     <code>git-conveyor-*</code> script to handle the resource action.
#  *   </div>
#  *   <div class="subHeader"><span>Platform Workarounds</span></div>
#  *   <div class="p">
#  *     Thanks to <a href=""></a> <a
#  *     href="https://github.com/nvie/gitflow">GitFlow</a> for these
#  *     workarounds. If you don't like our approach to branch management,
#  *     GitFlow offers a great alternative.
#  *   </div>
#  */

# If in future versions, we want to use shFlags for commandline option
# processing, we will want to set this variable, used by shFlags for
# compatibility purposes. As we don't currently do any option processing, it
# is not necessary.
# if uname -s | egrep -iq 'bsd'; then export EXPR_COMPAT=1; fi

# For Windows, we need to change '\' to '/'.
export GIT_CONVEY_DIR=$(dirname "$(echo "$0" | sed -e 's|\\|/|g')")

# Regularize getopt parsing across Linux platforms.
export POSIXLY_CORRECT=1

#/**
#  *   <div class="subHeader">Helper Functions and Usage Check</div>
#  *   <div class="p">
#  *     It's bash, so helper funtctions have to come first.
#  *   </div>
#  */

global_help() {
    echo "Use 'con help [<resource> [<action>]]' for details and refer to "
    echo "http://dogfoodsoftware.com/documentatione/conveyor/ref/Branching-Strategy for"
    echo "more on the underlying branch strategy which conveyor-workflow implements."
    echo
}

source "$HOME/.conveyor/config"
source "$GIT_CONVEY_DIR/lib/shflags"
source "$GIT_CONVEY_DIR/lib/resty"
source "$GIT_CONVEY_DIR/lib/rest-lib.sh"
source "$GIT_CONVEY_DIR/common-checks.sh"
source "$GIT_CONVEY_DIR/common-lib.sh"

RESOURCE="$1"; shift
source "$GIT_CONVEY_DIR/git-conveyor-$RESOURCE"

resource_do "$@"
#/**
#  * </div><!-- #Implementation.blurbSummary -->
#  */
