#!/bin/sh
#/**
#  * <div class="p">
#  * 'Controller' script for the <a
#  *   href="http://dogfoodsoftware.com/documentation/conveyor/ref/Branching-Strategy">Conveyor
#  *   branch strategy</a> extensions. Please refer to the branch strategy
#  *   documentation for details on usage.
#  * </div>
#  * <div id="Implementation" data-perspective="implementation" class="grid_12 blurbSummary">
#  *   <div class="blurbTitle">Implementation</div>
#  *   <div class="p">
#  *     This script essentially reads the first argument&mdash;which is
#  *     understood as the resource name&mdash;and then looks for the matching
#  *     <code>git-conveyor-*</code> script to handle the resource action.
#  *   </div>
#  *   <div class="subHeader"><span>Platform Workarounds</span></div>
#  *   <div class="p">
#  *     Thanks to <a href=""></a> <a
#  *     href="https://github.com/nvie/gitflow">GitFlow</a> for these
#  *     workarounds. If you don't like our approach to branch management,
#  *     GitFlow offers a great alternative.
#  *   </div>
#  */

# If in future versions, we want to use shFlags for commandline option
# processing, we will want to set this variable, used by shFlags for
# compatibility purposes. As we don't currently do any option processing, it
# is not necessary.
# if uname -s | egrep -iq 'bsd'; then export EXPR_COMPAT=1; fi

# For Windows, we need to change '\' to '/'.
export GIT_CONVEY_DIR=$(dirname "$(echo "$0" | sed -e 's|\\|/|g')")

# Regularize getopt parsing across Linux platforms.
export POSIXLY_CORRECT=1

#/**
#  *   <div class="subHeader">Helper Functions and Usage Check</div>
#  *   <div class="p">
#  *     It's bash, so helper funtctions have to come first.
#  *   </div>
#  */

global_help() {
    echo "Use 'con help [<resource> [<action>]]' for details and refer to "
    echo "http://dogfoodsoftware.com/documentatione/conveyor/ref/Branching-Strategy for"
    echo "more on the underlying branch strategy which conveyor-workflow implements."
    echo
}

# /**
#  * <div class="subHeader"><span>usage()</span></div>
#  * <div class="p">
#  *   Prints usage information for the <code>conveyor-workflow</code> script. Takes a
#  *   single optional argument, which is interpretted as a string containing
#  *   additional information about whyt he usage is being displayed. The error
#  *   is printed to <code>stderr</code>.
#  * </div>
#  */
usage() {
    if [ x"$1" != x"" ]; then
	echo $1 >&2
	echo >&2
    fi

    echo "usage: con <resource|global action>"
    echo
    echo "Available resources:"
    echo "   topics    Manage topics / topic branches."
    echo "   releases  Manage releases."
    echo
    echo "Available global actions:"
    echo "   sync      Clones and synchronizes local repo with origin."
    echo "   -s        Set implied resource."
    echo "   help      Prints this help."
    echo
    global_help
}

if [ $# -lt 1 ]; then
    usage "Please indicate resource."
    exit 1
fi

#/**
#  * <div class="subHeader"><span>Options Parsing</span></div>
#  */

source "$HOME/.conveyor/config"
source "$GIT_CONVEY_DIR/lib/shflags"
source "$GIT_CONVEY_DIR/lib/resty"
source "$GIT_CONVEY_DIR/lib/rest-lib.sh"
source "$GIT_CONVEY_DIR/common-checks.sh"
source "$GIT_CONVEY_DIR/common-lib.sh"
FLAGS_PARENT="git conveyor"

DEFINE_boolean verbose false 'be verbose => show git commands' 'v'
DEFINE_boolean test false 'run in test mode'

FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

if [ $FLAGS_test -eq $FLAGS_TRUE ]; then
    export GIT_CONVEY_TEST_MODE=$FLAGS_TRUE
fi

#/**
#* <div class="subHeader"><span>Main Logic</span></div>
#* <div class="p">
#*   Normally, we would process the arguments into named variables as a first
#*   step. In this case, the processing differences between 'implied
#*   resources' and 'explicit resources' means we have to do some work to
#*   establish the semantics of teh arguments.
#* </div>
#*/
if [ x"$1" == x"help" ]; then
    shift
    if [ $# -eq 0 ]; then
	usage
    else
	RESOURCE="$1"; shift
	source "$GIT_CONVEY_DIR/git-conveyor-$RESOURCE"
	if [ $# -eq 0 ]; then
	    resource_usage
	else
	    ACTION="$1"; shift
	    resource_help $ACTION
	fi
    fi
    exit 0
fi


if [ -f $HOME/.conveyor-workflow/implied-resource ]; then
    RESOURCE=`cat $HOME/.conveyor-workflow/implied-resource`
    source "$GIT_CONVEY_DIR/git-conveyor-$RESOURCE"
    if [ x`type -t action_check` != x'function' ]; then
	echo "WARNING: 'action_check' function not defined for '$RESOURCE'." >&2
	# Nothing else to do.
    else
	if ! action_check "$1" && ! con --verify "$1" >/dev/null; then
	    echo "ERROR: Cannot understand '$1' as action, resource, or global." >&2
	    exit 1
	elif con --verifyresource "$1" >/dev/null; then
	    rm -f $HOME/.conveyor-workflow/implied-resource
	    RESOURCE="$1"; shift
	    echo "WARNING: understood '$1' as resource; implied resource reset." >&2
	elif con --verifyglobal "$1" >/dev/null; then
	    RESOURCE="$1"; shift # and nothing else
	# else, it's an action of the implied resource, which is just fine
	fi
    fi
else
    RESOURCE="$1"; shift
fi

if [ ! -f "$GIT_CONVEY_DIR/git-conveyor-$RESOURCE" ]; then
    usage "Unknown resource: '$RESOURCE'."
    exit 1
fi
source "$GIT_CONVEY_DIR/git-conveyor-$RESOURCE"

resource_do "$@"
#/**
#  * </div><!-- #Implementation.blurbSummary -->
#  */
