#!/bin/sh
# /**
#  * <div class="p">
#  *   Script to implement 'topics' management within git. This is an
#  *   extension defined by <a
#  *   href="http://dogfoodsoftware.com/documentation/conveyor-workflow">Git
#  *   Convey</a>.
#  * </div>
#  * <div id="Implementation" data-perspective="implementation" class="grid_12 blurbSummary">

resource_usage() {
    if [ x"$1" != x"" ]; then
	echo $1 >&2
	echo >&2
    fi

    echo "usage: con topics [list [<topic pattern>]]|[start|checkout|commit|publish|delete|submit|abandon [topic]]|[help [action]]"
    echo
    echo "Available actions:"
    echo "   list      Lists open topics. This is the default action."
    echo "   start     Starts/opens a topic."
    echo "   checkout  Checks out an existing topic."
    echo "   commit    Commits changes to a topic."
    echo "   publish   Publishes changes to a topic."
    echo "   delete    Deletes the local topic branch."
    echo "   submit    Submits a topic branch for merge back to source."
    echo "   abandon   Abandons a topic branch."
    echo "   help      Print this help."
    echo
    global_help
}

resource_help() {
    if [ $# -lt 1 ]; then
	resource_usage
    else
	local ACTION="$1"; shift
	case "$ACTION" in
	    list)
		echo "Lists the topic branches active in the current repository."
		;;
	    start)
		echo "The branch name must start with the issue number for github cloned repos."
		;;
	    checkout)
		echo "Checks and and updates an existing topic branch."
		;;
	    commit)
		echo "Commits local changes to the topic branch."
		;;
	    publish)
		echo "Publishes the local changes to the origin repository."
		;;
	    delete)
		echo "Deletes the named topic branch from the local repository. To submit a topic"
		echo "for inclusion back to the source, use 'submit'."
		;;
	    submit)
		echo "Submits the topic branch for inclusion back to the source branch. I.e.,"
		echo "generate a pull request back to the origin."
		;;
	    abandon)
		echo "Archives a topic branch without submitting it for inclusion back to the"
		echo "source branch."
		;;
	    help)
		echo "Meta-help... you're blowing my mind."
		echo
		resource_usage;;
	    *)
		resource_usage "Unknown action: '$ACTION'."
		exit 1;
	esac
    fi
}

action_check() {
    local ACTION="$1"; shift

    case "$ACTION" in
	list|start|checkout|commit|publish|delete|submit|abandon|help)
	    return 0;;
	*)
	    return 1
    esac
}

resource_do() {
    if [ $# -eq 0 ]; then
	local ACTION="list"
    else
	local ACTION="$1"; shift
    fi

    case "$ACTION" in
	list)
	    list_resources topic;;
	start)
	    start_branch 'topics' "$@";;
	checkout)
	    checkout_branch 'topics' "$@";;
	commit)
	    commit_branch 'topics' "$@";;
	publish)
	    publish_branch 'topics' "$@";;
	delete)
	    delete_branch 'topics' "$@";;
	submit)
	    submit_branch 'topics' "$@";;
	abandon)
	    abandon_branch 'topics' "$@";;
	help)
	    if [ $# -eq 0 ]; then
		resource_usage
	    else
		resource_help "$1"
	    fi
	    ;;
	*)
	    resource_usage "Unknown action: '$ACTION'."
	    exit 1;
    esac
}
#  * </div><!-- #Implementation.blurbSummary -->
