#!/bin/sh
# /**
#  * <div class="p">
#  *   Script to implement 'topics' management within git. This is an
#  *   extension defined by <a
#  *   href="http://dogfoodsoftware.com/documentation/git-convey">Git
#  *   Convey</a>.
#  * </div>
#  * <div id="Implementation" data-perspective="implementation" class="grid_12 blurbSummary">

resource_usage() {
    if [ x"$1" != x"" ]; then
	echo $1 >&2
	echo >&2
    fi

    echo "usage: git convey topics [list [<topic pattern>]]|[start|checkout|commit|publish|delete|done|abandon [topic]]|[help [action]]"
    echo
    echo "Available actions:"
    echo "   list      Lists open topics. This is the default action."
    echo "   start     Starts/opens a topic."
    echo "   checkout  Checks out an existing topic."
    echo "   commit    Commits changes to a topic."
    echo "   publish   Publishes changes to a topic."
    echo "   delete    Deletes the local topic branch."
    echo "   done      Submits a topic branch."
    echo "   abandon   Abandons a topic branch."
    echo "   help      Print this help."
    echo
    global_help
}

resource_help() {
    if [ $# -lt 1 ]; then
	resource_usage
    else
	ACTION="$1"; shift
	case "$ACTION" in
	    list)
		echo "Lists the topic branches active in the current repository."
		;;
	    start)
		echo "Creates a new topic branch and checks it out. The current branch must be"
		echo "'master', which will be updated and used as the source of the new branch."
		echo "The branch must not already exist and the branch name must start with"
		echo "'task-', 'bugfix-', or 'hotfix-' as appropriate."
		;;
	    checkout)
		echo "Checks and and updates an existing topic branch."
		;;
	    commit)
		echo "Commits local changes to the topic branch."
		;;
	    publish)
		echo "Publishes the local changes to the origin repository."
		;;
	    delete)
		echo "Deletes the named topic branch from the local repository. To submit a topic"
		echo "for inclusion back to the source, use 'done'."
		;;
	    done)
		echo "Submits the topic branch for inclusion back to the source branch."
		;;
	    abandon)
		echo "Archives a topic branch without submitting it for inclusion back to the"
		echo "source branch."
		;;
	    help)
		echo "Meta-help... you're blowing my mind."
		echo
		resource_usage;;
	    *)
		resource_usage "Unknown action: '$ACTION'."
		exit 1;
	esac
    fi
}

resource_do() {
    if [ $# -lt 1 ]; then
	ACTION="list"
    else
	ACTION="$1"; shift
    fi

    case "$ACTION" in
	list)
	    list_resources topic;;
	start)
	    start_branch 'topics' "$@";;
	checkout)
	    checkout_branch 'topics' "$@";;
	commit)
	    commit_branch 'topics' "$@";;
	publish)
	    publish_branch 'topics' "$@";;
	delete)
	    echo delete;;
	done)
	    echo done;;
	abandon)
	    echo abondon;;
	help)
	    if [ $# -eq 0 ]; then
		resource_usage
	    else
		resource_help "$1"
	    fi
	    ;;
	*)
	    resource_usage "Unknown action: '$1'."
	    exit 1;
    esac
}
#  * </div><!-- #Implementation.blurbSummary -->
